---
- hosts: all
  sudo: yes

  tasks:
  - name: General | Install required packages.
    action: apt pkg={{ item }} state=installed update_cache=yes
    tags: common
    with_items:
      - build-essential
      - mysql-server
      - mysql-client
      - python-virtualenv
      - python3-dev
      - python3-apt
      - python3-pip
      - libmysqlclient-dev

  - name: Update virtualenv
    command: /usr/bin/pip3 install virtualenv==13.0.1

  - name: Install Requirements
    pip: chdir=/vagrant requirements=/vagrant/requirements.txt virtualenv=/vagrant/venv/
    sudo: yes

  - name: Create Database
    shell: mysql -u root -e "create database viewflows";
    ignore_errors: yes

  - name: Helpfull bash_profile
    copy: src=bash_profile dest=/home/vagrant/.bash_profile force=no